### ISSUE TITLE
Swiping triggers another in the list to also swipe 

### ISSUE THREAD

**Issue by msmith1992** [cinsola/XamarinSwipeListView#3]
When I swipe to delete on the first item, another item in the list also deletes and goes red.
Is this a problem with the ListView cell re-use perhaps?

Many Thanks

**Comment by cinsola** [comment]
Hi. Its a Xamarin' forms bug :/

**Comment by Zure1** [comment]
@cinsola @msmith1992  seems like it's not fixed by Xamarin 3.3. Did you happen to find a fix for this?

**Comment by cinsola** [comment]
fixed
